
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author eleni
 */
public class StarWarsCarouselWithTimer extends javax.swing.JFrame {

    /**
     * Creates new form StarWarsCarousel
     */
    public StarWarsCarouselWithTimer() {
        initComponents();
        MinL1.setIcon(minarray[0]);
        MinL2.setIcon(minarray[1]);
        MinL3.setIcon(minarray[2]);
        BasicLabel.setIcon(maxarray[1]);
        Timer timer = new Timer(3000, TimeActionListener);
        timer.setRepeats(true);
        timer.start();
    }
    
    ActionListener TimeActionListener = new ActionListener(){
        public void actionPerformed(ActionEvent actionEvent){
            index--;
            if(index == 0){
                MinL1.setIcon(minarray[minarray.length-1]);
                MinL2.setIcon(minarray[index]);
                MinL3.setIcon(minarray[index+1]);
                BasicLabel.setIcon(maxarray[index]);
            }else if(index == -1){
                index=minarray.length-1;
                MinL1.setIcon(minarray[index-1]);
                MinL2.setIcon(minarray[index]);
                MinL3.setIcon(minarray[0]);
                BasicLabel.setIcon(maxarray[index]);
            }else{
                MinL1.setIcon(minarray[index-1]);
                MinL2.setIcon(minarray[index]);
                MinL3.setIcon(minarray[index+1]);
                BasicLabel.setIcon(maxarray[index]);
            }
        }
    };
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BasicLabel = new javax.swing.JLabel();
        MinL1 = new javax.swing.JLabel();
        MinL2 = new javax.swing.JLabel();
        MinL3 = new javax.swing.JLabel();

        setTitle("Star Wars Carousel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(MinL1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(MinL2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(MinL3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(BasicLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(BasicLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MinL2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MinL1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MinL3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StarWarsCarousel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StarWarsCarousel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StarWarsCarousel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StarWarsCarousel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StarWarsCarouselWithTimer().setVisible(true);
            }
        });
    }

    int index = 1;
    ImageIcon hansolo = new ImageIcon("HanSolo.jpg");
    ImageIcon luke = new ImageIcon("LukeSky.jpg");
    ImageIcon organa = new ImageIcon("Organa.jpg");
    ImageIcon r2d2 = new ImageIcon("R2D2.jpg");
    ImageIcon c3po = new ImageIcon("c3po.jpg");
    ImageIcon rey = new ImageIcon("rey.jpg");
    ImageIcon minhansolo = new ImageIcon("HanSoloMin.jpg");
    ImageIcon minluke = new ImageIcon("LukeSkyMin.jpg");
    ImageIcon minorgana = new ImageIcon("OrganaMin.jpg");
    ImageIcon minr2d2 = new ImageIcon("R2D2Min.jpg");
    ImageIcon minc3po = new ImageIcon("c3poMin.jpg");
    ImageIcon minrey = new ImageIcon("reyMin.jpg");
    ImageIcon minarray[] = {minhansolo, minluke, minorgana, minr2d2, minc3po, minrey};
    ImageIcon maxarray[] = {hansolo, luke, organa, r2d2, c3po, rey};
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BasicLabel;
    private javax.swing.JLabel MinL1;
    private javax.swing.JLabel MinL2;
    private javax.swing.JLabel MinL3;
    // End of variables declaration//GEN-END:variables
}
